# Generated by Django 3.1.2 on 2020-11-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='buy_price',
            field=models.PositiveSmallIntegerField(default='Not provided'),
        ),
    ]
