# Generated by Django 3.1.2 on 2020-11-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0003_auto_20201102_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='buy_price',
            field=models.PositiveIntegerField(blank=True, default='Not provided', null=True),
        ),
    ]
