# Generated by Django 3.1.2 on 2020-11-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0008_auto_20201103_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
