# Generated by Django 3.1.2 on 2020-11-03 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0013_auto_20201103_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type_of_weapon',
            old_name='type',
            new_name='weapon',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='additional',
        ),
        migrations.AddField(
            model_name='type_of_weapon',
            name='additional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dayz_app.weapon'),
        ),
    ]
