# Generated by Django 3.1.2 on 2020-11-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0017_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='scopes',
        ),
        migrations.AddField(
            model_name='scope',
            name='weapons',
            field=models.ManyToManyField(related_name='scopes', to='dayz_app.Weapon'),
        ),
    ]
