# Generated by Django 3.1.2 on 2020-11-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0018_auto_20201103_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='weapons',
        ),
        migrations.AddField(
            model_name='weapon',
            name='scopes',
            field=models.ManyToManyField(related_name='weapon_scopes', to='dayz_app.Scope'),
        ),
    ]
