# Generated by Django 3.1.2 on 2020-11-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0019_auto_20201103_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='scopes',
            field=models.ManyToManyField(blank=True, default='No scope provided', null=True, related_name='weapon_scopes', to='dayz_app.Scope'),
        ),
    ]
