# Generated by Django 3.1.2 on 2020-11-12 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('magnitude', models.CharField(choices=[('x2.5', 'x2.5'), ('x3', 'x3'), ('x4', 'x4'), ('x5', 'x5'), ('x6', 'x6'), ('x7', 'x7'), ('x8', 'x8'), ('x12', 'x12'), ('x25', 'x25'), ('Other', 'Other')], default='Magnitude not defined', max_length=64)),
                ('sell_price', models.PositiveIntegerField()),
                ('buy_price', models.PositiveIntegerField(blank=True, default='Not provided', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sniper rifle', 'Sniper rifle'), ('Shotgun', 'Shotgun'), ('Assault rifle', 'Assault rifle'), ('Machine gun', 'Machine gun'), ('Rifle', 'Rifle'), ('Pistol', 'Pistol'), ('Submachine gun', 'Submachine gun')], default='Weapon type not defined', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('sell_price', models.PositiveIntegerField()),
                ('buy_price', models.PositiveIntegerField(blank=True, default='Not provided', null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('cal', models.CharField(choices=[('.308', '.308'), ('7.62x54', '7.62x54'), ('7.62x39', '7.62x39'), ('5.56x45', '5.56x45'), ('5.45x39', '5.45x39'), ('12ga', '12ga'), ('.357', '.357'), ('9mm', '9mm'), ('.338', '.338'), ('.408', '.408'), ('.50', '.50'), ('.45 ACP', '.45 ACP')], default='Caliber not defined', max_length=60)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='plakaty')),
                ('additional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dayz_app.type_of_weapon')),
                ('scopes', models.ManyToManyField(blank=True, default='No scope provided', related_name='weapon_scopes', to='dayz_app.Scope')),
            ],
        ),
    ]
