# Generated by Django 3.1.2 on 2020-11-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('sell_price', models.PositiveSmallIntegerField()),
                ('buy_price', models.PositiveSmallIntegerField(blank=True, default='')),
                ('description', models.TextField(default='')),
                ('cal', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('weapon_type', models.CharField(choices=[('Sniper rifle', 'Sniper rifle'), ('Shotgun', 'Shotgun'), ('Assault Rifle', 'Assault Rifle')], default='Weapon type not defined', max_length=60)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='plakaty')),
            ],
        ),
    ]
