# Generated by Django 3.1.2 on 2021-01-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='buy_price',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
