# Generated by Django 3.1.2 on 2020-11-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('.308', '.308'), ('7.62x54', '7.62x54'), ('7.62x39', '7.62x39'), ('5.56x45', '5.56x45'), ('5.45x39', '5.45x39'), ('12ga', '12ga'), ('.357', '.357'), ('9mm', '9mm'), ('.338', '.338'), ('.408', '.408'), ('.50', '.50'), ('.45 ACP', '.45 ACP')], default='Caliber not defined', max_length=60)),
                ('init_speed', models.PositiveSmallIntegerField()),
                ('health_damage', models.PositiveSmallIntegerField()),
                ('blood_damage', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
