# Generated by Django 3.1.2 on 2021-01-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0002_auto_20210115_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='buy_price',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
