# Generated by Django 3.1.2 on 2020-11-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0002_ammo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_ammo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('.308', '.308'), ('7.62x54', '7.62x54'), ('7.62x39', '7.62x39'), ('5.56x45', '5.56x45'), ('5.45x39', '5.45x39'), ('12ga', '12ga'), ('.357', '.357'), ('9mm', '9mm'), ('.338', '.338'), ('.408', '.408'), ('.50', '.50'), ('.45 ACP', '.45 ACP')], default='Caliber not defined', max_length=60)),
                ('init_speed', models.PositiveSmallIntegerField()),
                ('health_damage', models.PositiveSmallIntegerField()),
                ('blood_damage', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ammo',
            name='name',
            field=models.CharField(default='Not provided', max_length=60),
        ),
        migrations.AlterField(
            model_name='ammo',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dayz_app.type_of_ammo'),
        ),
    ]
