# Generated by Django 3.1.2 on 2021-01-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0003_auto_20210119_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='sell_price',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
