# Generated by Django 3.1.2 on 2020-11-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0003_auto_20201124_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ammo',
            name='blood_damage',
        ),
        migrations.RemoveField(
            model_name='type_of_ammo',
            name='blood_damage',
        ),
    ]
