# Generated by Django 3.1.2 on 2020-11-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0006_auto_20201102_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='weapon_type',
        ),
        migrations.CreateModel(
            name='type_of_weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(choices=[('Sniper rifle', 'Sniper rifle'), ('Shotgun', 'Shotgun'), ('Assault Rifle', 'Assault Rifle')], default='Weapon type not defined', max_length=60)),
                ('additional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dayz_app.weapon')),
            ],
        ),
    ]
