# Generated by Django 3.1.2 on 2020-11-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0010_auto_20201103_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_of_weapon',
            name='additional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dayz_app.weapon'),
        ),
    ]
