# Generated by Django 3.1.2 on 2020-11-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0011_auto_20201103_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type_of_weapon',
            name='additional',
        ),
        migrations.AddField(
            model_name='type_of_weapon',
            name='additional',
            field=models.ManyToManyField(to='dayz_app.Weapon'),
        ),
    ]
