# Generated by Django 3.1.2 on 2020-11-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayz_app', '0021_auto_20201109_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_of_weapon',
            name='type',
            field=models.CharField(choices=[('Sniper rifle', 'Sniper rifle'), ('Shotgun', 'Shotgun'), ('Assault rifle', 'Assault rifle'), ('Machine gun', 'Machine gun'), ('Rifle', 'Rifle'), ('Pistol', 'Pistol'), ('Submachine gun', 'Submachine gun')], default='Weapon type not defined', max_length=60),
        ),
    ]
